---
- hosts: localhost
  gather_facts: no
  
  vars:
  
    # dictionary selected variable
    vm_size: vm_small

    # dictionary of values to query
    vm_spec: [
      { key: vm_small,  cpu: 1, ram: 2  },
      { key: vm_medium, cpu: 2, ram: 4  },
      { key: vm_large,  cpu: 4, ram: 8  },
      { key: vm_xlarge, cpu: 8, ram: 16 }
    ]

  tasks:
    
    - name: make new dynamic list
      set_fact:
        that_list: "{{ that_list|default([]) + this_list }}"
      loop: "{{ vm_spec }}"
      vars:
        this_list: [ { name: "{{item.key}}", cpu: "{{item.cpu}}", ram: "{{item.ram}}" } ]

    - name: DEBUG - vm_spec
      debug: var=vm_spec


    - name: DEBUG - that_list
      debug: var=that_list