---
- hosts: localhost
  gather_facts: no
  
  vars:
  
    # dictionary of values to query
    old_list: [
      { key: vm_small,  cpu: 1, ram: 2  },
      { key: vm_medium, cpu: 2, ram: 4  },
      { key: vm_large,  cpu: 4, ram: 8  },
      { key: vm_xlarge, cpu: 8, ram: 16 }
    ]

  tasks:
    
    - name: make new dynamic list
      set_fact:
        new_list: "{{ new_list|default([]) + tmp_list }}"
      loop: "{{ old_list }}"
      vars:
        tmp_list: [ { name: "{{item.key}}", cpu: "{{item.cpu}}", ram: "{{item.ram}}" } ]

    - name: DEBUG - old_list
      debug: var=old_list

    - name: DEBUG - new_list
      debug: var=new_list