---
- hosts: localhost

  vars:

    # default to type "web" server
    profile: web


    # dictionary of logical volumes by server type
    vol_specs:
      general: []
      web: [
          { mount: sites,    pdevs: sdb }
        ]
      oracle: [
          { mount: apps,     pdevs: sdb },
          { mount: scratch,  pdevs: sdc },
          { mount: oradata,  pdevs: sdd },
          { mount: orafra,   pdevs: sde }
        ]
      mysql: [
          { mount: apps,     pdevs: sdb },
          { mount: scratch,  pdevs: sdc },
          { mount: mydata,   pdevs: sdd },
          { mount: mybackup, pdevs: sde }
        ]

  tasks:

    - name: paths
      debug:
        msg: "{{ '/dev/vg_' + item.mount + '/lv_' + item.mount }}"
      loop: "{{ vol_specs[profile] }}"

    - name: volumes
      debug:
        msg: "{{ '/dev/' + item.pdevs }}"
      loop: "{{ vol_specs[profile] }}"

#   https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#json-query-filter
#   - name: "Display all ports from cluster1 as a string"
#     debug:
#       msg: "{{ domain_definition | json_query('domain.server[?cluster==`cluster1`].port') | join(', ') }}"

#   $ ansible-playbook filesystems.yml -e srv_profile=oracle -e mountpt=oradata
    - name: Find apps in list
      set_fact:
#       entry: "[ {{ vol_specs | json_query('oracle[?mount==`apps`]') | join(', ') }} ]"
        entry: "[ {{ vol_specs[profile] | json_query('[?mount==`' + mountpt + '`]') | join(', ') }} ]"

    - name: Display found entry1
      debug:
        var: entry
