---
- hosts: localhost

  vars:

    # default to type "web" server
    srv_profile: web

    # dictionary of packages by server type
    pkg_specs:
      general: []
      web: [
        pkga,
        pkgb,
        pkgc
      ]
      oracle: [
        pkga,
        pkgb,
        pkgc
      ]
      mysql: [
        pkga,
        pkgb,
        pkgc
      ]

  tasks:

    - name: installing these packages
      debug:
        var: pkg_specs[srv_profile]

    # https://docs.ansible.com/ansible/latest/modules/package_module.html
    # package module evaluates client OS and calls appropriate apt or yum module
    - name: Install packages according to server profile "{{ srv_profile }}"
      package:
        name: "{{ pkg_specs[srv_profile] }}"
        state: present
