---
- hosts: localhost
  gather_facts: no

  vars_files:
    - server-specs.yml

  # From server-specs.yml
  #
  # vm_spec[vm_size].cpu, .ram (.ram must be '.ram * 1024')
  # os_spec[os_type].guest, .scsi, .nic, .image
  #
  # lvol, filesystem, win_partition specs
  # loop: fs_spec[fs_type] > item.vol {.mnt, .dev}
  #
  # win_partition specs
  # loop: fs_spec[fs_type] > item.vol {.letter, .psize, .pnum, .dnum}
  #
  # vmware_guest_disk specs
  # fs_spec[fs_type].dsk

  tasks:

    - debug: var=vm_vals
    - debug: var=os_vals
    - debug: var=fs_vals

    - name: get vm_size
      set_fact:
        profile: "{{ [ vm_size ] }}"

    # make sure we have a valid vm_size
    - name: validate vm_size
      fail:
        msg: Invalid size specification {{ vm_size }}
      when: profile is not subset(vm_vals)

    - name: get os_type
      set_fact:
        profile: "{{ [ os_type ] }}"

    # make sure we have a valid os_type
    - name: validate os_type
      fail:
        msg: Invalid operating system specificatino {{ os_type }}
      when: profile is not subset(os_vals)

    - name: get fs_type
      set_fact:
        profile: "{{ [ fs_type ] }}"

    # make sure we have a valid fs_type
    - name: validate fs_type
      fail:
        msg: Invalid filesystem specification {{ fs_type }}
      when: profile is not subset(fs_vals)

    - name: vm_size facts
      debug:
        var: vm_spec[vm_size].cpu

    - name: vm_size facts
      debug:
        var: vm_spec[vm_size].ram

    - name: os_type facts
      debug:
        var: os_spec[os_type].guest

    - name: fs_type facts
      debug:
        var: fs_spec[fs_type].dsk

    - name: fs_type facts
      debug:
        msg: "{{ item.mnt }} + ' ' + {{ item.dev }}"
      loop: "{{ fs_spec[fs_type].vol }}"
      when: fs_type != "mssql"

    - name: fs_type facts
      debug:
        msg: "{{ item.letter }} + ' ' + {{ item.psize }} + ' ' + {{ item.pnum }} + ' ' + {{ item.dnum }}"
      loop: "{{ fs_spec[fs_type].vol }}"
      when: fs_type == "mssql"
