---
- hosts: localhost
  gather_facts: no

  vars_files:
    - server-specs.yml

# esx_specs[vm_profile].cpu, .ram (.ram must be '.ram * 1024')
# esx_specs[os_profile].guest, .scsi, .nic, .image
#
# lvol, filesystem, win_partition specs
# loop: vol_specs[fs_profile] > item.vol {.mnt, .dev}
#
# win_partition specs
# loop: vol_specs[fs_profile] > item.vol {.letter, .psize, .pnum, .dnum}
#
# vmware_guest_disk specs
# vol_specs[fs_profile].dsk

  tasks:

    - name: vm_profile facts
      debug:
        var: esx_specs[vm_profile].cpu

    - name: vm_profile facts
      debug:
        var: esx_specs[vm_profile].ram

    - name: os_profile facts
      debug:
        var: esx_specs[os_profile].guest

    - name: fs_profile facts
      debug:
        var: vol_specs[fs_profile].dsk

    - name: fs_profile facts
      debug:
        msg: "{{ item.mnt }} + ' ' + {{ item.dev }}"
      loop: "{{ vol_specs[fs_profile].vol }}"
      when: fs_profile != "mssql"

    - name: fs_profile facts
      debug:
        msg: "{{ item.letter }} + ' ' + {{ item.psize }} + ' ' + {{ item.pnum }} + ' ' + {{ item.dnum }}"
      loop: "{{ vol_specs[fs_profile].vol }}"
      when: fs_profile == "mssql"

#     { letter: C, psize: -1, pnum: 1, dnum: 1 }, # C:

