---
- hosts: localhost
  gather_facts: no

  vars_files:
    - server-specs.yml

# esx_specs[vm_profile].cpu, .ram (.ram must be '.ram * 1024')
# esx_specs[os_profile].guest, .scsi, .nic, .image
#
# lvol, filesystem, win_partition specs
# loop: vol_specs[fs_profile] > item.vol {.mnt, .dev}
#
# win_partition specs
# loop: vol_specs[fs_profile] > item.vol {.letter, .psize, .pnum, .dnum}
#
# vmware_guest_disk specs
# vol_specs[fs_profile].dsk

  tasks:

    # make sure we have a valid vm_profile
    - name: validate vm_profile
      debug:
        msg: vm_profile "{{ vm_profile }}" is invalid
      when: [ "{{ vm_profile }}" ] is not subset(vm_profiles)

    # make sure we have a valid os_profile
    - name: validate os_profile
      debug:
        msg: os_profile "{{ os_profile }}" is invalid
      when: [ "{{ os_profile }}" ] is not subset(os_profiles)

    # make sure we have a valid fs_profile
    - name: validate fs_profile
      debug:
        msg: fs_profile "{{ fs_profile }}" is invalid
      when: [ "{{ fs_profile }}" ] is not subset(fs_profiles)

    - name: vm_profile facts
      debug:
        var: vm_specs[vm_profile].cpu

    - name: vm_profile facts
      debug:
        var: vm_specs[vm_profile].ram

    - name: os_profile facts
      debug:
        var: os_specs[os_profile].guest

    - name: fs_profile facts
      debug:
        var: vol_specs[fs_profile].dsk

    - name: fs_profile facts
      debug:
        msg: "{{ item.mnt }} + ' ' + {{ item.dev }}"
      loop: "{{ vol_specs[fs_profile].vol }}"
      when: fs_profile != "mssql"

    - name: fs_profile facts
      debug:
        msg: "{{ item.letter }} + ' ' + {{ item.psize }} + ' ' + {{ item.pnum }} + ' ' + {{ item.dnum }}"
      loop: "{{ vol_specs[fs_profile].vol }}"
      when: fs_profile == "mssql"

