---
- hosts: localhost
  gather_facts: no

  vars:

    vms_list: [
      { name: vm1, os: redhat7, fs: general,   size: vm_small },
      { name: vm2, os: redhat7, fs: web,       size: vm_small },
      { name: vm3, os: redhat7, fs: oracle,    size: vm_large }
    ]

    mac_addr: [
      "00:00:00:00:00:00",
      "00:00:00:00:00:44",
      "00:00:00:00:00:FF"
    ]

  tasks:

    # imagine we have looped through creating VMs using vmware_guest and "registered" the
    # facts after each one to make a list that we then use to make a list of mac addresses,
    # then we want to register each of those mac addresses with infblox using the name from
    # the vms_list list.

    - debug:
        msg: VM “{{ item.0.name }}" has MAC address is “{{ item.1 }}”
      with_together:
        - "{{ vms_list }}"
        - "{{ mac_addr }}"
