---
- hosts: localhost
  gather_facts: no

  vars:

    vms_list1: [
      { name: vm1, os: redhat7 },
      { name: vm2, os: redhat7 },
      { name: vm3, os: redhat7 }
    ]

    vms_list2: [
      { fs: general,   size: vm_small },
      { fs: web,       size: vm_small },
      { fs: oracle,    size: vm_large }
    ]

    mac_addr: [
      "00:00:00:00:00:00",
      "00:00:00:00:00:44",
      "00:00:00:00:00:FF"
    ]

  tasks:

    # imagine we have looped through creating VMs using vmware_guest and "registered" the
    # facts after each one to make a list that we then use to make a list of mac addresses,
    # then we want to register each of those mac addresses with infblox using the name from
    # the vms_list list.

    - debug:
        msg: "VM {{ item.0.name }} has size {{ item.1.size }} and MAC address {{ item.2 }}"
      with_together:
        - "{{ vms_list1 }}"
        - "{{ vms_list2 }}"
        - "{{ mac_addr }}"
